#ifndef CANOPEN_OBJDIC_H_
#define CANOPEN_OBJDIC_H_
/**
 * @file canopen_objdic.h
 * @brief 
 * @author YangDing(502552742@qq.com)
 * @version 1.0
 * @date 2022-03-05
 * 
 * @copyright Copyright (c) 2022  Panda
 * 
 * @par 修改日志:
 * <table>
 * <tr><th>Date       <th>Version <th>Author      <th>Description
 * <tr><td>2022-03-05 <td>1.0     <td>YangDing     <td>内容
 * </table>
 */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/*****************************************************************************
 *	Object dictionary operation type definition
 *****************************************************************************/
#define CANOPEN_SDO_MASTER                          0x600

#define CANOPEN_WRITE_DATA_T_INTEGER32              0x23
#define CANOPEN_WRITE_DATA_T_UNSIGNED32             0x23
#define CANOPEN_WRITE_DATA_T_UNSIGNED16             0x2B
#define CANOPEN_WRITE_DATA_T_INTEGER8               0x2F

/*****************************************************************************
 *	Object dictionary data type definition
 *****************************************************************************/
#define CANOPEN_DATA_T_RECORD						0x00
#define CANOPEN_DATA_T_BOOLEAN						0x01
#define CANOPEN_DATA_T_INTEGER8						0x02
#define CANOPEN_DATA_T_INTEGER16					0x03
#define CANOPEN_DATA_T_INTEGER32					0x04
#define CANOPEN_DATA_T_UNSIGNED8					0x05
#define CANOPEN_DATA_T_UNSIGNED16					0x06
#define CANOPEN_DATA_T_UNSIGNED32					0x07
#define CANOPEN_DATA_T_REAL32						0x08
#define CANOPEN_DATA_T_VISIBLE_STRING				0x09
#define CANOPEN_DATA_T_OCTET_STRING					0x0A
#define CANOPEN_DATA_T_UNICODE_STRING				0x0B
#define CANOPEN_DATA_T_TIME_OF_DAY					0x0C
#define CANOPEN_DATA_T_TIME_DIFFERENCE				0x0D
#define CANOPEN_DATA_T_DOMAIN						0x0E
#define CANOPEN_DATA_T_INTEGER24					0x0F
#define CANOPEN_DATA_T_REAL64						0x10
#define CANOPEN_DATA_T_INTEGER40					0x11
#define CANOPEN_DATA_T_INTEGER48					0x12
#define CANOPEN_DATA_T_INTEGER56					0x13
#define CANOPEN_DATA_T_INTEGER64					0x14
#define CANOPEN_DATA_T_UNSIGNED24					0x15
#define CANOPEN_DATA_T_UNSIGNED40					0x16
#define CANOPEN_DATA_T_UNSIGNED48					0x17
#define CANOPEN_DATA_T_UNSIGNED56					0x18
#define CANOPEN_DATA_T_UNSIGNED64					0x19
#define CANOPEN_DATA_T_PDO_COMMUNICATION_PARAMETER	0x1A
#define CANOPEN_DATA_T_PDO_MAPPING					0x1B
#define CANOPEN_DATA_T_SDO_PARAMETER				0x1C
#define CANOPEN_DATA_T_IDENTITY						0x1D

typedef struct _STRUCT_OBEJECT {
    uint16_t 					Index;
    uint8_t						SubIndex;
    uint8_t						DataType;
} STRUCT_OBEJECT;

static const STRUCT_OBEJECT RW_OBJ_MODES_OF_PROTOCOL                ={0x2002, 1, CANOPEN_DATA_T_UNSIGNED16};
static const STRUCT_OBEJECT RO_OBJ_ERROR_CODE                    	={0x603f, 0, CANOPEN_DATA_T_UNSIGNED16};
static const STRUCT_OBEJECT RW_OBJ_CTRL_WORD_REGISTER         		={0x6040, 0, CANOPEN_DATA_T_UNSIGNED16};
    #define	CTRL_WORD_DISABLE_VOLTAGE				0x0000				
    #define	CTRL_WORD_QUICK_STOP					0x0002				
    #define	CTRL_WORD_READY  						0x0006	
    #define	CTRL_WORD_SWITCH_ON						0x0007		
    #define	CTRL_WORD_ENABLE_OPERATION				0x000F				
    #define CTRL_WORD_CLEAR_ENCODER					0x1000		    /* bit 12 */		
    #define	CTRL_WORD_FAULT_RESET					0x0080	
static const STRUCT_OBEJECT RO_OBJ_STATUS_WORD_REGISTER          	={0x6041, 0, CANOPEN_DATA_T_UNSIGNED16};
    #define STATUS_WORD_BIT_NOT_SET					0x0000
    #define STATUS_WORD_READY_TO_SWITCH_ON			0x0001
    #define STATUS_WORD_SWITCHED_ON					0x0002				
    #define STATUS_WORD_OPERATION_ENABLED			0x0004	
    #define STATUS_WORD_FAULT						0x0008
    #define STATUS_WORD_VOLTAGE_ENABLED				0x0010	
    #define STATUS_WORD_QUICK_STOP					0x0020
    #define STATUS_WORD_SWITCH_ON_DISABLED			0x0040	        /* Initialization finished */
    #define STATUS_WORD_WARNING						0x0080
static const STRUCT_OBEJECT RW_OBJ_QUICK_STOP_OPTION_CODE        	={0x605A, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RW_OBJ_SHUTDOWN_OPTION_CODE          	={0x605B, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RW_OBJ_DISABLE_OPERATION_OPTION_CODE 	={0x605C, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RW_OBJ_HALT_OPTION_CODE              	={0x605D, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RW_OBJ_FAULT_REACTION_OPTION_CODE    	={0x605E, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RW_OBJ_MODES_OF_OPERATION            	={0x6060, 0, CANOPEN_DATA_T_INTEGER8};
    #define OPERATION_MODE_NOMODE                   0               /* 0 :No Mode/Mode is not assigned. */
    #define OPERATION_MODE_PROFILE_POSITION         1               /* 1 :(pp) Profile Position Mode */
    #define OPERATION_MODE_VELOCITY                 2               /* 2 :(vl) Velocity Mode*/
    #define OPERATION_MODE_PROFILE_VELOCITY         3               /* 3 :(pv) Profile Velocity Mode */
    #define OPERATION_MODE_TORQUE_PROFILE           4               /* 4 :(tp) Torque (force) Profile Mode */
    #define OPERATION_MODE_RESERVE                  5               /* 5 :Reserved Mode*/
    #define OPERATION_MODE_HOMING                   6               /* 6 :(hm) Homing Mode */
    #define OPERATION_MODE_INTERPOLATED_POSITION    7               /* 7 :(ip) Interpolated position mode */
    #define OPERATION_MODE_CYCLE_SYNC_POSITION      8               /* 8 :(csp) Cycle Sync. Position Mode */
    #define OPERATION_MODE_CYCLE_SYNC_VELOCITY      9               /* 9 :(csv) Cycle Sync. Velocity Mode */
    #define OPERATION_MODE_CYCLE_SYNC_TORQUE        10              /* 10:(cst) Cycle Sync. Torque (force) Mode */
static const STRUCT_OBEJECT RO_OBJ_MODES_OF_OPERATION_DISPLAY    	={0x6061, 0, CANOPEN_DATA_T_INTEGER8};
static const STRUCT_OBEJECT RO_OBJ_POSITION_DEMAND_VALUE         	={0x6062, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RO_OBJ_POSITION_ACTUAL_INTERNAL_VALUE	={0x6063, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RO_OBJ_POSITION_ACTUAL_VALUE 			={0x6064, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_FOLLOWING_ERROR_WINDOW        	={0x6065, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_FOLLOWING_ERROR_TIMEOUT       	={0x6066, 0, CANOPEN_DATA_T_UNSIGNED16};
static const STRUCT_OBEJECT RW_OBJ_POSITION_WINDOW               	={0x6067, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_POSITION_WINDOW_TIMEOUT       	={0x6068, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RO_OBJ_VELOCITY_SENSOR_ACTUAL_VALUE  	={0x6069, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_SENSOR_SELECTION_CODE         	={0x606A, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RO_OBJ_VELOCITY_DEMAND_VALUE         	={0x606B, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RO_OBJ_VELOCITY_ACTUAL_VALUE         	={0x606C, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_VELOCITY_WINDOW               	={0x606D, 0, CANOPEN_DATA_T_UNSIGNED16};
static const STRUCT_OBEJECT RW_OBJ_VELOCITY_WINDOW_TIME          	={0x606E, 0, CANOPEN_DATA_T_UNSIGNED16};
static const STRUCT_OBEJECT RW_OBJ_VELOCITY_THRESHOLD            	={0x606F, 0, CANOPEN_DATA_T_UNSIGNED16};
static const STRUCT_OBEJECT RW_OBJ_VELOCITY_THRESHOLD_TIME       	={0x6070, 0, CANOPEN_DATA_T_UNSIGNED16};
static const STRUCT_OBEJECT RW_OBJ_TARGET_TORQUE                 	={0x6071, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RW_OBJ_MAX_TORQUE                    	={0x6072, 0, CANOPEN_DATA_T_UNSIGNED16};
static const STRUCT_OBEJECT RW_OBJ_MAX_CURRENT                   	={0x6073, 0, CANOPEN_DATA_T_UNSIGNED16};
static const STRUCT_OBEJECT RO_OBJ_TORQUE_DEMAND                  	={0x6074, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RO_OBJ_MOTOR_RATED_CURRENT            	={0x6075, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RO_OBJ_MOTOR_RATED_TORQUE             	={0x6076, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RO_OBJ_TORQUE_ACTUAL_VALUE            	={0x6077, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RO_OBJ_CURRENT_ACTUAL_VALUE           	={0x6078, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RO_OBJ_DCLINK_CIRCUIT_VOLTAGE         	={0x6079, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_TARGET_POSITION                	={0x607A, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_POSITION_RANGE_LIMIT_MIN       	={0x607B, 1, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_POSITION_RANGE_LIMIT_MAX       	={0x607B, 2, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_HOME_OFFSET    			   		={0x607C, 2, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_SOFTWARE_POSITION_LIMIT_MIN    	={0x607D, 1, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_SOFTWARE_POSITION_LIMIT_MAX    	={0x607D, 2, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_POLARITY                       	={0x607E, 0, CANOPEN_DATA_T_INTEGER8};
static const STRUCT_OBEJECT RW_OBJ_MAX_PROFILE_VELOCITY           	={0x607F, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_MAX_MOTOR_SPEED                	={0x6080, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_PROFILE_VELOCITY               	={0x6081, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_END_VELOCITY                   	={0x6082, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_PROFILE_ACCELERATION           	={0x6083, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_PROFILE_DECELERATION           	={0x6084, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_QUICK_STOP_DECELERATION        	={0x6085, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_MOTION_PROFILE_TYPE            	={0x6086, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RW_OBJ_TORQUE_SLOPE                   	={0x6087, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_TORQUE_PROFILE_TYPEE               	={0x6088, 0, CANOPEN_DATA_T_INTEGER16};
static const STRUCT_OBEJECT RW_OBJ_POSITION_ENCODER_RESOLUTION_NUM	={0x608F, 1, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_POSITION_ENCODER_RESOLUTION_DEN	={0x608F, 2, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_VELOCITY_ENCODER_RESOLUTION_NUM	={0x6090, 1, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_VELOCITY_ENCODER_RESOLUTION_DEN	={0x6090, 2, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_GEAR_RATIO_NUM                 	={0x6091, 1, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_GEAR_RATIO_DEN                 	={0x6091, 2, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_FEED_CONSTANT_NUM            	={0x6092, 1, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_FEED_CONSTANT_DEN         		={0x6092, 2, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_VELOCITY_FACTOR_NUM            	={0x6096, 1, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_VELOCITY_FACTOR_DEN            	={0x6096, 2, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_ACCELERATION_FACTOR_NUM        	={0x6097, 1, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_ACCELERATION_FACTOR_DEN        	={0x6097, 2, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_HOMING_METHOD        			={0x6098, 0, CANOPEN_DATA_T_INTEGER8};
static const STRUCT_OBEJECT RW_OBJ_HOMING_ACCELERATION        		={0x609A, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RO_OBJ_POSITION_OFFSET        			={0x60B0, 0, CANOPEN_DATA_T_INTEGER32}; 
static const STRUCT_OBEJECT RO_OBJ_VELOCITY_OFFSET	       			={0x60B1, 0, CANOPEN_DATA_T_INTEGER32}; 
static const STRUCT_OBEJECT RO_OBJ_TORQUE_OFFSET         			={0x60B2, 0, CANOPEN_DATA_T_INTEGER16}; 
static const STRUCT_OBEJECT RW_OBJ_TOUCH_PROBE_FUNCTION				={0x60B8, 0, CANOPEN_DATA_T_UNSIGNED16};
static const STRUCT_OBEJECT RO_OBJ_TOUCH_PROBE_STATUS				={0x60B9, 0, CANOPEN_DATA_T_UNSIGNED16}; 
static const STRUCT_OBEJECT RO_OBJ_TOUCH_PROBE_POS_1_POS_VALUE		={0x60BA, 0, CANOPEN_DATA_T_INTEGER32}; 
static const STRUCT_OBEJECT RO_OBJ_TOUCH_PROBE_POS_1_NEG_VALUE		={0x60BB, 0, CANOPEN_DATA_T_INTEGER32}; 
static const STRUCT_OBEJECT RO_OBJ_TOUCH_PROBE_POS_2_POS_VALUE		={0x60BC, 0, CANOPEN_DATA_T_INTEGER32}; 
static const STRUCT_OBEJECT RO_OBJ_TOUCH_PROBE_POS_2_NEG_VALUE		={0x60BD, 0, CANOPEN_DATA_T_INTEGER32}; 
static const STRUCT_OBEJECT RW_OBJ_MAX_ACCELERATION               	={0x60C5, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_MAX_DECELERATION               	={0x60C6, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RW_OBJ_POSITIVE_TORQUE_LIMIT_VALUE		={0x60E0, 0, CANOPEN_DATA_T_UNSIGNED16}; 
static const STRUCT_OBEJECT RW_OBJ_NEGATIVE_TORQUE_LIMIT_VALUE		={0x60E1, 0, CANOPEN_DATA_T_UNSIGNED16}; 
static const STRUCT_OBEJECT RO_OBJ_FOLLOWING_ERROR_ACTUAL_VALUE   	={0x60F4, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RO_OBJ_CONTROL_EFFORT                 	={0x60FA, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RO_OBJ_POSITION_DEMAND_INTERNAL_VALUE 	={0x60FC, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RO_OBJ_DIGITAL_INPUTS 					={0x60FD, 0, CANOPEN_DATA_T_UNSIGNED32};
static const STRUCT_OBEJECT RO_OBJ_TARGET_VELOCITY                	={0x60FF, 0, CANOPEN_DATA_T_INTEGER32};
static const STRUCT_OBEJECT RW_OBJ_MOTOR_TYPE						={0x6402, 0, CANOPEN_DATA_T_UNSIGNED16}; 
static const STRUCT_OBEJECT RO_OBJ_SUPPORTED_DRIVE_MODES          	={0x6502, 0, CANOPEN_DATA_T_UNSIGNED32};


#ifdef __cplusplus
}
#endif	
#endif
